ESX = exports.es_extended:getSharedObject()

Teamchat = {
    ['inhaber'] = true,
    ['pl'] = true,
    ['highteam'] = true,
    ['support'] = true,
    ['guide'] = true,
    ['dev'] = true
}

Announce = {
    ['inhaber'] = true,
    ['pl'] = true,
    ['highteam'] = true,
    ['dev'] = true
}

Weapons = {
    [GetHashKey('WEAPON_DAGGER')] = 'DAGGER',
    [GetHashKey('WEAPON_BAT')] = 'Baseballschläger',
    [GetHashKey('WEAPON_BOTTLE')] = 'BOTTLE',
    [GetHashKey('WEAPON_CROWBAR')] = 'CROWBAR',
    [GetHashKey('WEAPON_UNARMED')] = 'UNARMED',
    [GetHashKey('WEAPON_FLASHLIGHT')] = 'Taschenlampe',
    [GetHashKey('WEAPON_GOLFCLUB')] = 'Golfschläger',
    [GetHashKey('WEAPON_HAMMER')] = 'Hammer',
    [GetHashKey('WEAPON_HATCHET')] = 'WEAPON_HATCHET',
    [GetHashKey('WEAPON_KNUCKLE')] = 'WEAPON_KNUCKLE',
    [GetHashKey('WEAPON_KNIFE')] = 'Messer',
    [GetHashKey('WEAPON_MACHETE')] = 'Machete',
    [GetHashKey('WEAPON_SWITCHBLADE')] = 'Klappmesser',
    [GetHashKey('WEAPON_NIGHTSTICK')] = 'Schlagstock',
    [GetHashKey('WEAPON_WRENCH')] = 'WRENCH',
    [GetHashKey('WEAPON_BATTLEAXE')] = 'BATTLEAXE',
    [GetHashKey('WEAPON_POOLCUE')] = 'POOLCUE',
    [GetHashKey('WEAPON_STONE_HATCHET')] = 'STONE HATCHET',
    -- Pistol's
    [GetHashKey('WEAPON_PISTOL')] = 'Pistole',
    [GetHashKey('WEAPON_PISTOL_MK2')] = 'Pistole Mk2',
    [GetHashKey('WEAPON_COMBATPISTOL')] = 'Combat Pistole',
    [GetHashKey('WEAPON_APPISTOL')] = 'AP Pistole',
    [GetHashKey('WEAPON_STUNGUN')] = 'Tazer',
    [GetHashKey('WEAPON_PISTOL50')] = '50er Pistole',
    [GetHashKey('WEAPON_SNSPISTOL')] = 'SNS Pistole',
    [GetHashKey('WEAPON_SNSPISTOL_MK2')] = 'SNS Pistole Mk2',
    [GetHashKey('WEAPON_HEAVYPISTOL')] = 'Schwere Pistole',
    [GetHashKey('WEAPON_VINTAGEPISTOL')] = 'Vintage Pistole',
    [GetHashKey('WEAPON_FLAREGUN')] = 'DAGGER',
    [GetHashKey('WEAPON_MARKSMANPISTOL')] = 'MARKSMANPISTOL',
    [GetHashKey('WEAPON_REVOLVER')] = 'Revolver',
    [GetHashKey('WEAPON_REVOLVER_MK2')] = 'Revolver Mk2',
    [GetHashKey('WEAPON_DOUBLEACTION')] = 'DOUBLEACTION',
    [GetHashKey('WEAPON_RAYPISTOL')] = 'RAYPISTOL',
    [GetHashKey('WEAPON_CERAMICPISTOL')] = 'CERAMICPISTOL',
    [GetHashKey('WEAPON_NAVYREVOLVER')] = 'NAVYREVOLVER',
    [GetHashKey('WEAPON_GADGETPISTOL')] = 'GADGETPISTOL',
    -- SMG's
    [GetHashKey('WEAPON_MICROSMG')] = 'Micro SMG',
    [GetHashKey('WEAPON_SMG')] = 'SMG',
    [GetHashKey('WEAPON_SMG_MK2')] = 'SMG Mk2',
    [GetHashKey('WEAPON_ASSAULTSMG')] = 'WEAPON_ASSAULTSMG',
    [GetHashKey('WEAPON_COMBATPDW')] = 'Combat PDW',
    [GetHashKey('WEAPON_MACHINEPISTOL')] = 'Maschinen Pistole',
    [GetHashKey('WEAPON_MINISMG')] = 'Mini SMG',
    [GetHashKey('WEAPON_RAYCARBINE')] = 'WEAPON_RAYCARBINE',
    -- Shotgun's
    [GetHashKey('WEAPON_PUMPSHOTGUN')] = 'Pumpgun',
    [GetHashKey('WEAPON_PUMPSHOTGUN_MK2')] = 'Pumpgun Mk2',
    [GetHashKey('WEAPON_SAWNOFFSHOTGUN')] = 'WEAPON_SAWNOFFSHOTGUN',
    [GetHashKey('WEAPON_ASSAULTSHOTGUN')] = 'WEAPON_ASSAULTSHOTGUN',
    [GetHashKey('WEAPON_BULLPUPSHOTGUN')] = 'WEAPON_BULLPUPSHOTGUN',
    [GetHashKey('WEAPON_MUSKET')] = 'WEAPON_MUSKET',
    [GetHashKey('WEAPON_HEAVYSHOTGUN')] = 'WEAPON_HEAVYSHOTGUN',
    [GetHashKey('WEAPON_DBSHOTGUN')] = 'WEAPON_DBSHOTGUN',
    [GetHashKey('WEAPON_AUTOSHOTGUN')] = 'WEAPON_AUTOSHOTGUN',
    [GetHashKey('WEAPON_COMBATSHOTGUN')] = 'WEAPON_COMBATSHOTGUN',
    -- Rifle's
    [GetHashKey('WEAPON_ASSAULTRIFLE')] = 'Sturmgewehr',
    [GetHashKey('WEAPON_ASSAULTRIFLE_MK2')] = 'Sturmgewehr Mk2',
    [GetHashKey('WEAPON_CARBINERIFLE')] = 'Karabiner',
    [GetHashKey('WEAPON_CARBINERIFLE_MK2')] = 'Karabiner Mk2',
    [GetHashKey('WEAPON_ADVANCEDRIFLE')] = 'WEAPON_ADVANCEDRIFLE',
    [GetHashKey('WEAPON_SPECIALCARBINE')] = 'Spezial Karabiner',
    [GetHashKey('WEAPON_SPECIALCARBINE_MK2')] = 'Spezial Karabiner Mk2',
    [GetHashKey('WEAPON_BULLPUPRIFLE')] = 'WEAPON_BULLPUPRIFLE',
    [GetHashKey('WEAPON_BULLPUPRIFLE_MK2')] = 'WEAPON_BULLPUPRIFLE_MK2',
    [GetHashKey('WEAPON_COMPACTRIFLE')] = 'WEAPON_COMPACTRIFLE',
    [GetHashKey('WEAPON_MILITARYRIFLE')] = 'WEAPON_MILITARYRIFLE',
    [GetHashKey('WEAPON_HEAVYRIFLE')] = 'WEAPON_HEAVYRIFLE',
    [GetHashKey('WEAPON_TACTICALRIFLE')] = 'WEAPON_TACTICALRIFLE',
    -- MG's
    [GetHashKey('WEAPON_MG')] = 'WEAPON_MG',
    [GetHashKey('WEAPON_COMBATMG')] = 'WEAPON_COMBATMG',
    [GetHashKey('WEAPON_COMBATMG_MK2')] = 'WEAPON_COMBATMG_MK2',
    [GetHashKey('WEAPON_GUSENBERG')] = 'Gusenberg',
    -- Sniper's
    [GetHashKey('WEAPON_SNIPERRIFLE')] = 'WEAPON_SNIPERRIFLE',
    [GetHashKey('WEAPON_HEAVYSNIPER')] = 'WEAPON_HEAVYSNIPER',
    [GetHashKey('WEAPON_HEAVYSNIPER_MK2')] = 'WEAPON_HEAVYSNIPER_MK2',
    [GetHashKey('WEAPON_MARKSMANRIFLE')] = 'WEAPON_MARKSMANRIFLE',
    [GetHashKey('WEAPON_MARKSMANRIFLE_MK2')] = 'WEAPON_MARKSMANRIFLE_MK2',
    [GetHashKey('WEAPON_PRECISIONRIFLE')] = 'WEAPON_PRECISIONRIFLE',
    -- Heavies
    [GetHashKey('WEAPON_RPG')] = 'RPG',
    [GetHashKey('WEAPON_GRENADELAUNCHER')] = 'Granatenwerfer',
    [GetHashKey('WEAPON_GRENADELAUNCHER_SMOKE')] = 'Rauchgranatenwerfer',
    [GetHashKey('WEAPON_MINIGUN')] = 'Minigun',
    [GetHashKey('WEAPON_FIREWORK')] = 'WEAPON_FIREWORK',
    [GetHashKey('WEAPON_RAILGUN')] = 'WEAPON_RAILGUN',
    [GetHashKey('WEAPON_HOMINGLAUNCHER')] = 'WEAPON_HOMINGLAUNCHER',
    [GetHashKey('WEAPON_COMPACTLAUNCHER')] = 'WEAPON_COMPACTLAUNCHER',
    [GetHashKey('WEAPON_RAYMINIGUN')] = 'Ray Minigun',
    [GetHashKey('WEAPON_EMPLAUNCHER')] = 'EMP Launcher',
    -- Throwables
    [GetHashKey('WEAPON_GRENADE')] = 'WEAPON_GRENADE',
    [GetHashKey('WEAPON_BZGAS')] = 'WEAPON_BZGAS',
    [GetHashKey('WEAPON_MOLOTOV')] = 'WEAPON_MOLOTOV',
    [GetHashKey('WEAPON_STICKYBOMB')] = 'WEAPON_STICKYBOMB',
    [GetHashKey('WEAPON_PROXMINE')] = 'WEAPON_PROXMINE',
    [GetHashKey('WEAPON_SNOWBALL')] = 'WEAPON_SNOWBALL',
    [GetHashKey('WEAPON_PIPEBOMB')] = 'WEAPON_PIPEBOMB',
    [GetHashKey('WEAPON_BALL')] = 'WEAPON_BALL',
    [GetHashKey('WEAPON_SMOKEGRENADE')] = 'WEAPON_SMOKEGRENADE',
    [GetHashKey('WEAPON_FLARE')] = 'WEAPON_FLARE',
    -- Other's
    [GetHashKey('WEAPON_PETROLCAN')] = 'Petrol Can',
    [GetHashKey('GADGET_PARACHUTE')] = 'Fallschirm',
    [GetHashKey('WEAPON_FIREEXTINGUISHER')] = 'WEAPON_FIREEXTINGUISHER',
}